### ISSUE TITLE
glooctl: get vs route panics

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#1220]
```
$ glooctl get vs route default

panic: interface conversion: interface {} is []*v1.Route, not []*v1.Route (types from different scopes)

goroutine 1 [running]:
github.com/solo-io/gloo/projects/gloo/cli/pkg/printers.PrintRoutes.func1(0x31d6540, 0xc000bfbbc0, 0x3ad00e0, 0xc000010010, 0x0, 0x0)
	/Users/eitanya/go/src/github.com/solo-io/gloo/projects/gloo/cli/pkg/printers/route.go:35 +0xbf
github.com/solo-io/gloo/vendor/github.com/solo-io/go-utils/cliutils.PrintList(0x35cbef4, 0x5, 0x0, 0x0, 0x31d6540, 0xc000bfbbc0, 0x369b038, 0x3ad00e0, 0xc000010010, 0x0, ...)
	/Users/eitanya/go/src/github.com/solo-io/gloo/vendor/github.com/solo-io/go-utils/cliutils/printers.go:81 +0x282
github.com/solo-io/gloo/projects/gloo/cli/pkg/printers.PrintRoutes(0xc000a80020, 0x1, 0x1, 0x0, 0x0, 0x0)
	/Users/eitanya/go/src/github.com/solo-io/gloo/projects/gloo/cli/pkg/printers/route.go:33 +0xee
github.com/solo-io/gloo/projects/gloo/cli/pkg/cmd/get.Routes.func1(0xc000a06000, 0xc00095b640, 0x1, 0x1, 0x0, 0x0)
	/Users/eitanya/go/src/github.com/solo-io/gloo/projects/gloo/cli/pkg/cmd/get/virtualservice.go:54 +0x43f
github.com/solo-io/gloo/vendor/github.com/spf13/cobra.(*Command).execute(0xc000a06000, 0xc00095b5f0, 0x1, 0x1, 0x0, 0x0)
	/Users/eitanya/go/src/github.com/solo-io/gloo/vendor/github.com/spf13/cobra/command.go:762 +0xb21
github.com/solo-io/gloo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0009bf680, 0xc000a06000, 0x0, 0x0)
	/Users/eitanya/go/src/github.com/solo-io/gloo/vendor/github.com/spf13/cobra/command.go:852 +0x677
github.com/solo-io/gloo/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0009bf680, 0x0, 0x0)
	/Users/eitanya/go/src/github.com/solo-io/gloo/vendor/github.com/spf13/cobra/command.go:800 +0x3b
main.main()
	/Users/eitanya/go/src/github.com/solo-io/gloo/projects/gloo/cli/cmd/main.go:15 +0x94
```

**Comment by rickducott** [comment]
Closing as stale
