### ISSUE TITLE
`Glooctl get virtualservice route` command panics

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1350]
Steps to reproduce:
* Deploy petclinic (`kubectl apply \
  --filename https://raw.githubusercontent.com/sololabs/demos2/master/resources/petstore.yaml`)
* create a VS (`glooctl add route \
    --path-exact /sample-route-1 \
    --dest-name default-petstore-8080 \
    --prefix-rewrite /api/pets`)
* run `glooctl get vs route default`

Results in:
```shell
panic: interface conversion: interface {} is []*v1.Route, not []*v1.Route (types from different scopes)

goroutine 1 [running]:
github.com/solo-io/gloo/projects/gloo/cli/pkg/printers.PrintRoutes.func1(0x3233580, 0xc000783a60, 0x3b3afc0, 0xc0000ee000, 0x0, 0x0)
	/private/tmp/glooctl-20191007-77277-1r44abr/src/github.com/solo-io/gloo/projects/gloo/cli/pkg/printers/route.go:35 +0xbf
github.com/solo-io/gloo/vendor/github.com/solo-io/go-utils/cliutils.PrintList(0x364ed50, 0x5, 0x0, 0x0, 0x3233580, 0xc000783a60, 0x3722940, 0x3b3afc0, 0xc0000ee000, 0x0, ...)
	/private/tmp/glooctl-20191007-77277-1r44abr/src/github.com/solo-io/gloo/vendor/github.com/solo-io/go-utils/cliutils/printers.go:81 +0x297
github.com/solo-io/gloo/projects/gloo/cli/pkg/printers.PrintRoutes(0xc000768790, 0x1, 0x1, 0x0, 0x0, 0x0)
	/private/tmp/glooctl-20191007-77277-1r44abr/src/github.com/solo-io/gloo/projects/gloo/cli/pkg/printers/route.go:33 +0xee
github.com/solo-io/gloo/projects/gloo/cli/pkg/cmd/get.Routes.func1(0xc000920c80, 0xc0006075f0, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/glooctl-20191007-77277-1r44abr/src/github.com/solo-io/gloo/projects/gloo/cli/pkg/cmd/get/virtualservice.go:54 +0x441
github.com/solo-io/gloo/vendor/github.com/spf13/cobra.(*Command).execute(0xc000920c80, 0xc0006075a0, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/glooctl-20191007-77277-1r44abr/src/github.com/solo-io/gloo/vendor/github.com/spf13/cobra/command.go:762 +0xb21
github.com/solo-io/gloo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000920500, 0xc000920c80, 0x0, 0x0)
	/private/tmp/glooctl-20191007-77277-1r44abr/src/github.com/solo-io/gloo/vendor/github.com/spf13/cobra/command.go:852 +0x678
github.com/solo-io/gloo/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000920500, 0x0, 0x0)
	/private/tmp/glooctl-20191007-77277-1r44abr/src/github.com/solo-io/gloo/vendor/github.com/spf13/cobra/command.go:800 +0x3b
main.main()
	/private/tmp/glooctl-20191007-77277-1r44abr/src/github.com/solo-io/gloo/projects/gloo/cli/cmd/main.go:15 +0x94
```

**Comment by kdorosh** [comment]
Also, the suggested command help is wrong (should be `Long:    "usage: glooctl get virtualservice route [virtualservice name]",`)

**Comment by kdorosh** [comment]
Working on a fix, cause is related to import errors likely related to CLI merge
