### ISSUE TITLE
Validation panic

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#1873]
Seeing this error when doing initial Virtual Service deployment - possible upstream is not fully ready yet. Gloo pod crash

```
{"level":"info","ts":1575999629.1006653,"logger":"gloo-ee.v1.event_loop","caller":"v1/setup_event_loop.sk.go:57","msg":"event loop started","version":"undefined"}
{"level":"info","ts":1575999629.6621058,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop","caller":"v1/eds_event_loop.sk.go:57","msg":"event loop started","version":"undefined"}
{"level":"info","ts":1575999630.143593,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop","caller":"v1/api_event_loop.sk.go:57","msg":"event loop started","version":"undefined"}
{"level":"info","ts":1575999631.721793,"logger":"gloo-ee.v1.event_loop.gloo.metrics","caller":"runner/run.go:50","msg":"Starting metrics server","version":"undefined"}
{"level":"info","ts":1575999631.721855,"logger":"gloo-ee.v1.event_loop.gloo.metrics","caller":"runner/run.go:56","msg":"metrics server running in [gRPC] mode, listening at [:9966]","version":"undefined"}
{"level":"info","ts":1575999632.8828552,"caller":"cache/simple.go:224","msg":"open watch 1 for type.googleapis.com/glooe.solo.io.RateLimitConfig[] from nodeID \"ratelimit\", version \"\""}
{"level":"info","ts":1575999633.631025,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer","caller":"discovery/run.go:33","msg":"begin sync 14172817109806179342 (57 upstreams)","version":"undefined"}
{"level":"info","ts":1575999635.179112,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.envoyTranslatorSyncer","caller":"syncer/envoy_translator_syncer.go:58","msg":"begin sync 16238681107483186448 (1 proxies, 57 upstreams, 0 endpoints, 2 secrets, 15 artifacts, 0 auth configs)","version":"undefined"}
{"level":"info","ts":1575999637.0318434,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer","caller":"discovery/discovery.go:184","msg":"Received first EDS update from plugin: *ec2.plugin","version":"undefined"}
{"level":"info","ts":1575999637.150483,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer","caller":"discovery/run.go:63","msg":"end sync 14172817109806179342","version":"undefined"}
{"level":"info","ts":1575999637.151746,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer","caller":"discovery/discovery.go:184","msg":"Received first EDS update from plugin: *kubernetes.plugin","version":"undefined"}
{"level":"info","ts":1575999637.7588205,"caller":"cache/simple.go:224","msg":"open watch 2 for type.googleapis.com/envoy.api.v2.Cluster[] from nodeID \"gloo-system~gateway-proxy\", version \"17661227228104261798\""}
{"level":"info","ts":1575999637.75891,"caller":"cache/simple.go:224","msg":"open watch 3 for type.googleapis.com/envoy.api.v2.Listener[] from nodeID \"gloo-system~gateway-proxy\", version \"12705146030334592124\""}
{"level":"info","ts":1575999637.7761433,"caller":"cache/simple.go:224","msg":"open watch 4 for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment[gloo-system-rate-limit-18081_gloo-system gloo-system-gloo-9977_gloo-system default-petclinic-db-3306_gloo-system kube-svc:default-kubernetes-443_default kube-system-metrics-server-v0-3-1-443_gloo-system rate-limit_gloo-system gloo-system-redis-6379_gloo-system kube-system-heapster-v1-7-1-80_gloo-system kube-svc:kube-system-kube-dns-53_kube-system kube-svc:gloo-system-glooe-prometheus-server-80_gloo-system kube-svc:gloo-system-gateway-proxy-80_gloo-system kube-svc:gloo-system-apiserver-ui-8080_gloo-system default-petclinic-db-petclinic-db-0-3306_gloo-system kube-svc:gloo-system-gateway-proxy-443_gloo-system kube-svc:gloo-system-extauth-8083_gloo-system kube-svc:default-petclinic-vets-8080_default kube-svc:gloo-system-glooe-grafana-80_gloo-system gloo-system-glooe-prometheus-ku-534dc85ecaea4d8dcdb77d98b192015_gloo-system gloo-system-gateway-proxy-gateway-proxy-443_gloo-system kube-svc:default-petstore-8080_default kube-svc:kube-system-default-http-backend-80_kube-system gloo-system-glooe-prometheus-server-80_gloo-system gloo-system-glooe-grafana-80_gloo-system gloo-system-gloo-9988_gloo-system gloo-system-gateway-proxy-gateway-proxy-80_gloo-system kube-svc:gloo-system-gloo-9988_gloo-system kube-system-heapster-80_gloo-system gloo-system-gloo-9966_gloo-system extauth_gloo-system gloo-system-glooe-prometheus-kube-state-metrics-80_gloo-system gloo-system-gateway-proxy-443_gloo-system gloo-system-apiserver-ui-gloo-8080_gloo-system kube-svc:default-petclinic-8080_default gloo-system-glooe-prometheus-server-prometheus-9-3-1-helm-80_gloo-system kube-svc:gloo-system-gloo-9977_gloo-system default-petstore-8080_gloo-system kube-svc:gloo-system-redis-6379_gloo-system gloo-system-gateway-443_gloo-system default-petclinic-8080_gloo-system kube-svc:default-petclinic-db-3306_default kube-system-default-http-backend-80_gloo-system gloo-system-gateway-proxy-80_gloo-system gloo-system-extauth-8083_gloo-system kube-svc:kube-system-metrics-server-443_kube-system kube-system-metrics-server-443_gloo-system default-petclinic-vets-8080_gloo-system default-kubernetes-443_gloo-system kube-svc:kube-system-heapster-80_kube-system kube-system-default-http-backend-glbc-80_gloo-system kube-svc:gloo-system-rate-limit-18081_gloo-system gloo-system-apiserver-ui-8080_gloo-system kube-system-kube-dns-53_gloo-system kube-svc:gloo-system-glooe-prometheus-kube-state-metrics-80_gloo-system kube-svc:gloo-system-gloo-9966_gloo-system kube-svc:gloo-system-gateway-443_gloo-system] from nodeID \"gloo-system~gateway-proxy\", version \"17661227228104261798-10320975177172178297\""}
{"level":"info","ts":1575999637.7762847,"caller":"cache/simple.go:224","msg":"open watch 5 for type.googleapis.com/envoy.api.v2.RouteConfiguration[listener-::-8080-routes] from nodeID \"gloo-system~gateway-proxy\", version \"10629566362751462596\""}
{"level":"info","ts":1575999638.1424146,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.envoyTranslatorSyncer.translator","caller":"translator/translator.go:114","msg":"computing envoy resources for listener: listener-::-8080","version":"undefined"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x229f32f]

goroutine 404 [running]:
github.com/solo-io/gloo/projects/gloo/pkg/validation.(*validator).ValidateProxy(0xc0009291a0, 0x3735e80, 0xc0005641e0, 0xc000564240, 0x0, 0x0, 0x0)
	/workspace/gopath/pkg/mod/github.com/solo-io/gloo@v1.2.4/projects/gloo/pkg/validation/server.go:42 +0x8f
github.com/solo-io/gloo/projects/gloo/pkg/validation.(*validationServer).ValidateProxy(0xc000db61c0, 0x3735e80, 0xc0005641e0, 0xc000564240, 0x0, 0x0, 0x0)
	/workspace/gopath/pkg/mod/github.com/solo-io/gloo@v1.2.4/projects/gloo/pkg/validation/server.go:91 +0xe0
github.com/solo-io/gloo/projects/gloo/pkg/api/grpc/validation._ProxyValidationService_ValidateProxy_Handler(0x2cfcf80, 0xc000db61c0, 0x3735e80, 0xc0005641e0, 0xc000b67e60, 0x0, 0x0, 0x0, 0x0, 0x0)
	/workspace/gopath/pkg/mod/github.com/solo-io/gloo@v1.2.4/projects/gloo/pkg/api/grpc/validation/proxy_validation.pb.go:1134 +0x3df
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0007e1b00, 0x3756c20, 0xc000ba4000, 0xc00271bb00, 0xc0009294a0, 0x5109510, 0x0, 0x0, 0x0)
	/workspace/gopath/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1007 +0x105e
google.golang.org/grpc.(*Server).handleStream(0xc0007e1b00, 0x3756c20, 0xc000ba4000, 0xc00271bb00, 0x0)
	/workspace/gopath/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1287 +0x976
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc002a21180, 0xc0007e1b00, 0x3756c20, 0xc000ba4000, 0xc00271bb00)
	/workspace/gopath/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:722 +0xb5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/workspace/gopath/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:720 +0xb0
```

deploying this simple Virtual service

```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-petclinic-8080
            namespace: gloo-system
```

to reproduce, I was running in a GKE 1.14 (regular channel) cluster with Gloo Ent 1.0.0-rc4 using this script

https://github.com/solo-io/demos-gloo/blob/656f838036fde3b44e24644defd849f116a19fad/petclinic_demo/run_petclinic_demo.sh

deleting the virtual service and then re applying got everything to a working state, so I'm guessing this is a race condition when an upstream is not quite ready.

**Comment by GrahamGoudeau** [comment]
https://github.com/solo-io/gloo/pull/1894
