### ISSUE TITLE
nil pointer in the oauth syncer

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2681]
A user reported a nil pointer in the gloo exauth pod when trying to load an oauth secret that had the right gloo fields and some other fields as well. 

We should add a nil check for the oauth field of the secret specifically and return an error in this case. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2a17906]
goroutine 292 [running]:
github.com/solo-io/solo-projects/projects/gloo/pkg/plugins/extauth.translateOauth(0xc001746160, 0xc000b9e880, 0x0, 0x0, 0x0)
        /workspace/gopath/src/github.com/solo-io/solo-projects/projects/gloo/pkg/plugins/extauth/translate.go:171 +0x96
github.com/solo-io/solo-projects/projects/gloo/pkg/plugins/extauth.translateConfig(0x3969ca0, 0xc001720810, 0xc001746160, 0xc00
1e75c50, 0x0, 0x0, 0x0)
        /workspace/gopath/src/github.com/solo-io/solo-projects/projects/gloo/pkg/plugins/extauth/translate.go:63 +0x7fa
github.com/solo-io/solo-projects/projects/gloo/pkg/plugins/extauth.TranslateExtAuthConfig(0x3969ca0, 0xc001720810, 0xc001746160
, 0xc0009d1b80, 0x0, 0x0, 0x0)
        /workspace/gopath/src/github.com/solo-io/solo-projects/projects/gloo/pkg/plugins/extauth/translate.go:34 +0x478
github.com/solo-io/solo-projects/projects/gloo/pkg/syncer/extauth.(*helper).processAuthExtension(0xc002232140, 0x3969ca0, 0xc00
1720810, 0xc001746160, 0xc0017da360, 0x0, 0x0)
        /workspace/gopath/src/github.com/solo-io/solo-projects/projects/gloo/pkg/syncer/extauth/extauth_translator_syncer.go:12
6 +0x17d
github.com/solo-io/solo-projects/projects/gloo/pkg/syncer/extauth.(*TranslatorSyncerExtension).SyncAndSet(0x4eeae50, 0x3969ca0,
 0xc001720810, 0xc001746160, 0x7f19dc124088, 0xc000098360, 0x0, 0x0)
        /workspace/gopath/src/github.com/solo-io/solo-projects/projects/gloo/pkg/syncer/extauth/extauth_translator_syncer.go:67
 +0x3bd
github.com/solo-io/solo-projects/projects/gloo/pkg/syncer/extauth.(*TranslatorSyncerExtension).Sync(0x4eeae50, 0x3969ca0, 0xc00
1720810, 0xc001746160, 0x39818a0, 0xc000098360, 0x0, 0x0)
        /workspace/gopath/src/github.com/solo-io/solo-projects/projects/gloo/pkg/syncer/extauth/extauth_translator_syncer.go:43
 +0x596
github.com/solo-io/gloo/projects/gloo/pkg/syncer.(*translatorSyncer).Sync(0xc0000c5650, 0x3969be0, 0xc000effe00, 0xc001746160,
0x0, 0x0)
        /workspace/gopath/pkg/mod/github.com/solo-io/gloo@v1.2.23/projects/gloo/pkg/syncer/translator_syncer.go:63 +0x24d
github.com/solo-io/gloo/projects/gloo/pkg/api/v1.ApiSyncers.Sync(0xc000a86a40, 0x2, 0x2, 0x3969be0, 0xc000effe00, 0xc001746160,
 0x0, 0x0)
        /workspace/gopath/pkg/mod/github.com/solo-io/gloo@v1.2.23/projects/gloo/pkg/api/v1/api_event_loop.sk.go:28 +0x104
github.com/solo-io/gloo/projects/gloo/pkg/api/v1.(*apiEventLoop).Run.func1(0xc00192e000, 0x3969ca0, 0xc000c41620, 0x0, 0xdf8475
800, 0x0, 0x0, 0xc000c415f0, 0xc00038ef60, 0xc001180078)
        /workspace/gopath/pkg/mod/github.com/solo-io/gloo@v1.2.23/projects/gloo/pkg/api/v1/api_event_loop.sk.go:84 +0x35f
created by github.com/solo-io/gloo/projects/gloo/pkg/api/v1.(*apiEventLoop).Run
        /workspace/gopath/pkg/mod/github.com/solo-io/gloo@v1.2.23/projects/gloo/pkg/api/v1/api_event_loop.sk.go:66 +0x3ef
```

**Comment by rickducott** [comment]
Different error also related to slightly malformed secret: 

```
{"level":"fatal","ts":1585911441.814917,"logger":"gloo-ee","caller":"setuputils/main_setup.go:87","msg":"error in setup: starting snapshot watch: initial Secret list: reading secret data into *v1.Secret: json: cannot unmarshal string into Go value of type map[string]json.RawMessage","version":"undefined","stacktrace":"github.com/solo-io/gloo/pkg/utils/setuputils.Main\n\t/workspace/gopath/pkg/mod/github.com/solo-io/gloo@v1.2.24/pkg/utils/setuputils/main_setup.go:87\ngithub.com/solo-io/solo-projects/projects/gloo/pkg/setup.Main\n\t/workspace/gopath/src/github.com/solo-io/solo-projects/projects/gloo/pkg/setup/setup.go:40\nmain.main\n\t/workspace/gopath/src/github.com/solo-io/solo-projects/projects/gloo/cmd/main.go:11\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
```
