### ISSUE TITLE
glooctl check SEGV

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3428]
**Describe the bug**

```
$ glooctl version
Client: {"version":"1.5.0-beta13"}
Server: {"type":"Gateway","enterprise":true,"kubernetes":{"containers":[{"Tag":"1.5.0-beta12","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.5.0-beta6","Name":"extauth-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.0-beta12","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.5.0-beta6","Name":"gloo-ee-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.5.0-beta6","Name":"gloo-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.0-beta6","Name":"rate-limit-ee","Registry":"quay.io/solo-io"},{"Tag":"5","Name":"redis","Registry":"docker.io"}],"namespace":"gloo-system"}}
```

```
$ glooctl -n gloo-system check
Checking deployments... OK
Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking auth configs... OK
Checking rate limit configs... OK
Checking secrets... OK
Checking virtual services... panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3746dce]

goroutine 1 [running]:
github.com/solo-io/gloo/projects/gloo/cli/pkg/cmd/check.renderRef(0x0, 0x0, 0x0)
	/workspace/gloo/projects/gloo/cli/pkg/cmd/check/root.go:548 +0x2e
github.com/solo-io/gloo/projects/gloo/cli/pkg/cmd/check.checkVirtualServices.func1(0x0, 0x0, 0x0, 0x0, 0x0)
	/workspace/gloo/projects/gloo/cli/pkg/cmd/check/root.go:420 +0x57
github.com/solo-io/gloo/projects/gloo/cli/pkg/cmd/check.checkVirtualServices(0xc0013b0020, 0x1, 0x1, 0xc000509700, 0xe, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/gloo/projects/gloo/cli/pkg/cmd/check/root.go:429 +0xd71
github.com/solo-io/gloo/projects/gloo/cli/pkg/cmd/check.CheckResources(0xc0001a2000, 0x0, 0x0, 0x0)
	/workspace/gloo/projects/gloo/cli/pkg/cmd/check/root.go:110 +0xb15
github.com/solo-io/gloo/projects/gloo/cli/pkg/cmd/check.RootCmd.func1(0xc000b7aa00, 0xc000a16fc0, 0x0, 0x2, 0x0, 0x0)
	/workspace/gloo/projects/gloo/cli/pkg/cmd/check/root.go:40 +0x5c
github.com/spf13/cobra.(*Command).execute(0xc000b7aa00, 0xc000a16f20, 0x2, 0x2, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0xb21
github.com/spf13/cobra.(*Command).ExecuteC(0xc00046a280, 0xc000b7aa00, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x698
github.com/spf13/cobra.(*Command).Execute(0xc00046a280, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864 +0x3b
main.main()
	/workspace/gloo/projects/gloo/cli/cmd/main.go:11 +0x34
```

**To Reproduce**
```
$ kubectl -n gloo-system get vs default -o yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  creationTimestamp: "2020-07-25T12:03:14Z"
  generation: 12
  name: default
  namespace: gloo-system
  resourceVersion: "194616"
  selfLink: /apis/gateway.solo.io/v1/namespaces/gloo-system/virtualservices/default
  uid: d18c4be1-ce6e-11ea-8041-42010aa800f5
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /api
      routeAction:
        single:
          upstream:
            name: gloo-system-petstore-8080
            namespace: gloo-system
status:
  reportedBy: gateway
  state: 1
  subresourceStatuses:
    '*v1.Proxy.gloo-system.gateway-proxy':
      reportedBy: gloo
      state: 1
```

**Expected behavior**

**Additional context**
Add any other context about the problem here, e.g.
- Gloo version
- Kubernetes version

**Comment by joekelley** [comment]
This should be addressed by https://github.com/solo-io/gloo/pull/3398 in the next release

**Comment by emayssat** [comment]
Same issue here ....
