### ISSUE TITLE
SIGSEGV in gloo pod with virtualservice sslConfig.sds

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3555]
**Describe the bug**
SIGSEGV in gloo pod with virtualservice sslConfig.sds

**To Reproduce**
Create VS with:
```
  sslConfig:
    sds:
      certificatesSecretName: foo
      validationContextName: bar
      targetUri: 127.0.0.1:8234
```

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x25584b9]

```
goroutine 502 [running]:
github.com/solo-io/gloo/projects/gloo/pkg/utils.buildSds(0xc001aadcb0, 0x3, 0xc0046914a0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.4.10/projects/gloo/pkg/utils/ssl.go:110 +0x69
github.com/solo-io/gloo/projects/gloo/pkg/utils.(*sslConfigTranslator).handleSds(0x5548770, 0xc0046914a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.4.10/projects/gloo/pkg/utils/ssl.go:171 +0x2dd
github.com/solo-io/gloo/projects/gloo/pkg/utils.(*sslConfigTranslator).ResolveCommonSslConfig(0x5548770, 0x3d1b4a0, 0xc002a80980, 0xc002713c00, 0x7, 0x8, 0x453f01, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.4.10/projects/gloo/pkg/utils/ssl.go:210 +0xd63
github.com/solo-io/gloo/projects/gloo/pkg/utils.(*sslConfigTranslator).ResolveDownstreamSslConfig(0x5548770, 0xc002713c00, 0x7, 0x8, 0xc002a80980, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.4.10/projects/gloo/pkg/utils/ssl.go:62 +0xba
github.com/solo-io/gloo/projects/gloo/pkg/translator.validateListenerSslConfig(0x3d0e0c0, 0xc0024c1650, 0xc000f42210, 0xc000da5560, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.4.10/projects/gloo/pkg/translator/route_config.go:677 +0x11a
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorInstance).computeRouteConfig(0xc001abefb8, 0x3d0e0c0, 0xc0024c1650, 0xc000f42210, 0xc001ace7e0, 0xc000da5560, 0xc004687220, 0x17, 0xc002b8d0e0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.4.10/projects/gloo/pkg/translator/route_config.go:54 +0x1ec
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorInstance).computeListenerResources(0xc00471efb8, 0x3d0e0c0, 0xc0024c1620, 0xc000f42210, 0xc001ace7e0, 0xc000da5560, 0xc002b8d0e0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.4.10/projects/gloo/pkg/translator/translator.go:186 +0x1ed
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorInstance).Translate(0xc00471efb8, 0x3d0e0c0, 0xc002a7fbf0, 0xc000f42210, 0xc001ace7e0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/solo-io/gloo@v1.4.10/projects/gloo/pkg/translator/translator.go:133 +0x1195
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorFactory).Translate(0xc000ae1be0, 0x3d0e0c0, 0xc002a7f8f0, 0xc000f42210, 0xc001ace7e0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/solo-io/gloo@v1.4.10/projects/gloo/pkg/translator/translator.go:47 +0x1b9
github.com/solo-io/gloo/projects/gloo/pkg/validation.(*validator).ValidateProxy(0xc000701310, 0x3d0e0c0, 0xc002a7f8f0, 0xc000ecc4e0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.4.10/projects/gloo/pkg/validation/server.go:170 +0x2d4
github.com/solo-io/gloo/projects/gloo/pkg/validation.(*validationServer).ValidateProxy(0xc0010305a0, 0x3d0e0c0, 0xc000ecc4b0, 0xc000ecc4e0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.4.10/projects/gloo/pkg/validation/server.go:217 +0xe0
github.com/solo-io/gloo/projects/gloo/pkg/api/grpc/validation._ProxyValidationService_ValidateProxy_Handler(0x32539a0, 0xc0010305a0, 0x3d0e0c0, 0xc000ecc4b0, 0xc004691440, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.4.10/projects/gloo/pkg/api/grpc/validation/proxy_validation.pb.go:1264 +0x3df
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004a0d00, 0x3d27b60, 0xc0006b5b00, 0xc002418600, 0xc000db35c0, 0x54c3a90, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.28.0-pre.0.20200226185027-6cd03861bfd2/server.go:1082 +0x1035
google.golang.org/grpc.(*Server).handleStream(0xc0004a0d00, 0x3d27b60, 0xc0006b5b00, 0xc002418600, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.28.0-pre.0.20200226185027-6cd03861bfd2/server.go:1405 +0x976
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc002438060, 0xc0004a0d00, 0x3d27b60, 0xc0006b5b00, 0xc002418600)
	/go/pkg/mod/google.golang.org/grpc@v1.28.0-pre.0.20200226185027-6cd03861bfd2/server.go:746 +0xf4
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.28.0-pre.0.20200226185027-6cd03861bfd2/server.go:744 +0xb0
```

**Comment by Sodman** [comment]
This looks like a bug in 1.4.x that was fixed in 1.5.0-beta20. Basically CallCredentials are required and there's no nil check on them before using. Here's the PR/lines that fixed it in 1.5: https://github.com/solo-io/gloo/pull/3507/files#diff-f6a0ec70700f90fa59bfe1584ded2565R112-R116
