### ISSUE TITLE
/admin path of the api-server UI isn't working when using Vault as the Secret Store

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#3735]
**Describe the bug**
As soon as Vault is configured as the Secret Store, the `/admin` path of the api-server UI become available with the following error:

```
{"level":"debug","ts":1602488309.0939608,"logger":"gloo-grpcserver","caller":"zap/server_interceptors.go:40","msg":"finished unary call with code OK","version":"1.4.14","grpc.start_time":"2020-10-12T07:38:29Z","system":"grpc","span.kind":"server","grpc.service":"glooeeapi.solo.io.ConfigApi","grpc.method":"ListNamespaces","grpc.code":"OK","grpc.time_ms":15.970999717712402}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f210d6]

goroutine 286 [running]:
github.com/hashicorp/vault/api.(*Client).NewRequest(0x0, 0x2f2f156, 0x4, 0xc000ac87e0, 0x30, 0x0)
	/go/pkg/mod/github.com/hashicorp/vault/api@v1.0.5-0.20191108163347-bdd38fca2cff/client.go:685 +0x46
github.com/hashicorp/vault/api.(*Logical).List(0xc00139e0b0, 0xc000ac87b0, 0x2c, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/hashicorp/vault/api@v1.0.5-0.20191108163347-bdd38fca2cff/logical.go:98 +0xe4
github.com/solo-io/solo-kit/pkg/api/v1/clients/vault.(*ResourceClient).listKeys(0xc000801740, 0xc000ac87b0, 0x2c, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/solo-kit@v0.13.8-patch4/pkg/api/v1/clients/vault/resource_client.go:237 +0xc1
github.com/solo-io/solo-kit/pkg/api/v1/clients/vault.(*ResourceClient).List(0xc000801740, 0x0, 0x0, 0x337d0e0, 0xc0006e4b10, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/solo-io/solo-kit@v0.13.8-patch4/pkg/api/v1/clients/vault/resource_client.go:188 +0x275
github.com/solo-io/gloo/projects/gloo/pkg/api/v1.(*secretClient).List(0xc0003fb040, 0x0, 0x0, 0x337d0e0, 0xc0006e4b10, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/solo-io/gloo@v1.4.13/projects/gloo/pkg/api/v1/secret_client.sk.go:88 +0x120
github.com/solo-io/solo-projects/projects/grpcserver/server/service/secretsvc.(*secretGrpcService).ListSecrets(0xc00014d360, 0x337d0e0, 0xc0009cf8f0, 0xc000c9ccc0, 0x0, 0x0, 0x0)
	/workspace/solo-projects/projects/grpcserver/server/service/secretsvc/service.go:61 +0x22d
github.com/solo-io/solo-projects/projects/grpcserver/api/v1._SecretApi_ListSecrets_Handler.func1(0x337d0e0, 0xc0009cf8f0, 0x2d52aa0, 0xc000c9ccc0, 0x0, 0x0, 0x0, 0x0)
	/workspace/solo-projects/projects/grpcserver/api/v1/secret.pb.go:850 +0x108
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x337d0e0, 0xc0009cf8f0, 0x2d52aa0, 0xc000c9ccc0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:31 +0xe5
github.com/solo-io/solo-projects/projects/grpcserver/server/logging.RequestResponseDebugInterceptor.func1(0x337d0e0, 0xc0009cf8f0, 0x2d52aa0, 0xc000c9ccc0, 0xc000c9cd00, 0xc000d30dc0, 0x0, 0x0, 0x0, 0x0)
	/workspace/solo-projects/projects/grpcserver/server/logging/interceptors.go:16 +0xb3
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x337d0e0, 0xc0009cf8f0, 0x2d52aa0, 0xc000c9ccc0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x24b
github.com/grpc-ecosystem/go-grpc-middleware/logging/zap.UnaryServerInterceptor.func1(0x337d0e0, 0xc0009cf7d0, 0x2d52aa0, 0xc000c9ccc0, 0xc000c9cd00, 0xc000d30dc0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/logging/zap/server_interceptors.go:32 +0x178
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x337d0e0, 0xc0009cf7d0, 0x2d52aa0, 0xc000c9ccc0, 0xc000c9cd00, 0xc000c9cd20, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:39 +0x24d
github.com/solo-io/solo-projects/projects/grpcserver/api/v1._SecretApi_ListSecrets_Handler(0x2c86940, 0xc00014d360, 0x337d0e0, 0xc0009cf7d0, 0xc000099e00, 0xc0008af860, 0x0, 0x0, 0x0, 0x0)
	/workspace/solo-projects/projects/grpcserver/api/v1/secret.pb.go:852 +0x24d
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0008f61a0, 0x3394d20, 0xc00061f200, 0xc00070ea00, 0xc0008afbc0, 0x488f1d8, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.28.0-pre.0.20200226185027-6cd03861bfd2/server.go:1082 +0x1035
google.golang.org/grpc.(*Server).handleStream(0xc0008f61a0, 0x3394d20, 0xc00061f200, 0xc00070ea00, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.28.0-pre.0.20200226185027-6cd03861bfd2/server.go:1405 +0x976
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000da03d0, 0xc0008f61a0, 0x3394d20, 0xc00061f200, 0xc00070ea00)
	/go/pkg/mod/google.golang.org/grpc@v1.28.0-pre.0.20200226185027-6cd03861bfd2/server.go:746 +0xf4
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.28.0-pre.0.20200226185027-6cd03861bfd2/server.go:744 +0xb0
```

I've simply removed the `kubernetesSecretSource` entry from the Settings object and added the following:

```
  vaultSecretSource:
    address: http://vault.default.svc.cluster.local:8200
    token: xxx
```

**Additional context**
- Gloo version 1.4.14

**Comment by jameshbarton** [comment]
@djannot now reports seeing this same behavior on 1.5.0, in addition to 1.4.14.
