### ISSUE TITLE
Upstream with wrong serviceNamespace can crash Gloo

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4006]
**Describe the bug**
When creating a kub Upstream with a `serviceNamespace:` pointing to a non-existing namespace, then Gloo can crash.

**Additional context**
- Gloo Edge version 1.5.12

**Stacktrace**
```json
{"level":"info","ts":1608294897.2685003,"logger":"gloo-ee.v1.event_loop","caller":"v1/setup_event_loop.sk.go:57","msg":"event loop started","version":"1.5.11"}
{"level":"info","ts":1608294899.5692146,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop","caller":"v1/eds_event_loop.sk.go:57","msg":"event loop started","version":"1.5.11"}
{"level":"info","ts":1608294899.6736295,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer","caller":"discovery/run.go:35","msg":"begin sync 10380848668149237812 (7 upstreams)","version":"1.5.11"}
{"level":"info","ts":1608294899.673777,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer","caller":"discovery/discovery.go:188","msg":"Received first EDS update from plugin: *ec2.plugin","version":"1.5.11"}
{"level":"info","ts":1608294899.7739289,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer","caller":"discovery/run.go:65","msg":"end sync 10380848668149237812","version":"1.5.11"}
{"level":"warn","ts":1608294899.7740855,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer.kubernetes_eds","caller":"kubernetes/eds.go:101","msg":"namespace is not watched, and has upstreams pointing to it","version":"1.5.11","namespace":"app-bla"}
{"level":"error","ts":1608294899.7741644,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer.kubernetes_eds","caller":"kubernetes/eds.go:206","msg":"upstream app.tpsvc-public-api-80: port 80 not found for service tpsvc-public-api","version":"1.5.11","stacktrace":"github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.filterEndpoints\n\t/go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/plugins/kubernetes/eds.go:206\ngithub.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*edsWatcher).List\n\t/go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/plugins/kubernetes/eds.go:121\ngithub.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*edsWatcher).watch.func1\n\t/go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/plugins/kubernetes/eds.go:130\ngithub.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*edsWatcher).watch.func2\n\t/go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/plugins/kubernetes/eds.go:150"}
{"level":"warn","ts":1608294899.7743926,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer.kubernetes_eds","caller":"kubernetes/eds.go:101","msg":"namespace is not watched, and has upstreams pointing to it","version":"1.5.11","namespace":"app-bla"}
{"level":"info","ts":1608294899.7744124,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer","caller":"discovery/discovery.go:188","msg":"Received first EDS update from plugin: *kubernetes.plugin","version":"1.5.11"}
{"level":"error","ts":1608294899.7744298,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer.kubernetes_eds","caller":"kubernetes/eds.go:206","msg":"upstream app.tpsvc-public-api-80: port 80 not found for service tpsvc-public-api","version":"1.5.11","stacktrace":"github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.filterEndpoints\n\t/go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/plugins/kubernetes/eds.go:206\ngithub.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*edsWatcher).List\n\t/go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/plugins/kubernetes/eds.go:121\ngithub.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*edsWatcher).watch.func1\n\t/go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/plugins/kubernetes/eds.go:130\ngithub.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*edsWatcher).watch.func2\n\t/go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/plugins/kubernetes/eds.go:157"}
{"level":"warn","ts":1608294899.7748766,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer.kubernetes_eds","caller":"kubernetes/eds.go:101","msg":"namespace is not watched, and has upstreams pointing to it","version":"1.5.11","namespace":"app-bla"}
{"level":"error","ts":1608294899.774934,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer.kubernetes_eds","caller":"kubernetes/eds.go:206","msg":"upstream app.tpsvc-public-api-80: port 80 not found for service tpsvc-public-api","version":"1.5.11","stacktrace":"github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.filterEndpoints\n\t/go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/plugins/kubernetes/eds.go:206\ngithub.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*edsWatcher).List\n\t/go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/plugins/kubernetes/eds.go:121\ngithub.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*edsWatcher).watch.func1\n\t/go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/plugins/kubernetes/eds.go:130\ngithub.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*edsWatcher).watch.func2\n\t/go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/plugins/kubernetes/eds.go:157"}
{"level":"info","ts":1608294899.775116,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop","caller":"v1/api_event_loop.sk.go:57","msg":"event loop started","version":"1.5.11"}
{"level":"info","ts":1608294899.8115745,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.envoyTranslatorSyncer","caller":"syncer/envoy_translator_syncer.go:77","msg":"begin sync 10516340518891382943 (2 proxies, 7 upstreams, 5 endpoints, 2 secrets, 630 artifacts, 0 auth configs, 0 rate limit configs)","version":"1.5.11"}
{"level":"info","ts":1608294899.811804,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.envoyTranslatorSyncer","caller":"runtime/panic.go:975","msg":"end sync 10516340518891382943","version":"1.5.11"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x25c1dd3]
goroutine 657 [running]:
github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*plugin).ProcessUpstream(0xc0010ef7c0, 0x40097c0, 0xc0034c0f00, 0xc002b84000, 0xc00b343680, 0xc000d3da40, 0x0, 0x0)
    /go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/plugins/kubernetes/plugin.go:64 +0x193
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorInstance).computeCluster(0xc0034b4bf8, 0x40097c0, 0xc0034c0f00, 0xc002b84000, 0xc00b343680, 0xc0034c0c00, 0x0)
    /go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/translator/clusters.go:52 +0x2d1
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorInstance).computeClusters(0xc0034b4bf8, 0x40097c0, 0xc0034c0db0, 0xc002b84000, 0xc0034c0c00, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/translator/clusters.go:36 +0x299
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorInstance).Translate(0xc0034b4bf8, 0x40097c0, 0xc0034c0ab0, 0xc002b84000, 0xc002eb4480, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/translator/translator.go:81 +0x688
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorFactory).Translate(0xc000722500, 0x40097c0, 0xc0034c0780, 0xc002b84000, 0xc002eb4480, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/translator/translator.go:47 +0x1b9
github.com/solo-io/gloo/projects/gloo/pkg/syncer.(*translatorSyncer).syncEnvoy(0xc0005c7700, 0x40097c0, 0xc0029b2c90, 0xc002b84000, 0x0, 0x0)
    /go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/syncer/envoy_translator_syncer.go:125 +0xd7f
github.com/solo-io/gloo/projects/gloo/pkg/syncer.(*translatorSyncer).Sync(0xc0005c7700, 0x4009700, 0xc0010ef3c0, 0xc002b84000, 0x0, 0x0)
    /go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/syncer/translator_syncer.go:63 +0x7e
github.com/solo-io/gloo/projects/gloo/pkg/api/v1.ApiSyncers.Sync(0xc000722780, 0x2, 0x2, 0x4009700, 0xc0010ef3c0, 0xc002b84000, 0x0, 0x0)
    /go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/api/v1/api_event_loop.sk.go:28 +0x104
github.com/solo-io/gloo/projects/gloo/pkg/api/v1.(*apiEventLoop).Run.func1(0xc0022c3440, 0x40097c0, 0xc001d27aa0, 0x0, 0xdf8475800, 0x0, 0x0, 0xc001d27a70, 0xc0015f07e0, 0xc0011890c0)
    /go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/api/v1/api_event_loop.sk.go:84 +0x35f
created by github.com/solo-io/gloo/projects/gloo/pkg/api/v1.(*apiEventLoop).Run
    /go/pkg/mod/github.com/solo-io/gloo@v1.5.12/projects/gloo/pkg/api/v1/api_event_loop.sk.go:66 +0x3ef
```

**Comment by jameshbarton** [comment]
I'm trying to reproduce this with gloo-ee 1.6.0-beta12.  I first created a valid US and VS and got them working as expected. Then I applied a change to the VS to point to the wrong `serviceNamespace`.  The gloo pod is spewing errors (2-3 per second), with messages like this:  `upstream gloo-system.us-bug-petclinic-8080: port 8080 not found for service petclinic`.

The dashboard also shows a reasonable error for the `Upstream`:
```
1 error occurred: * Upstream name:"us-bug-petclinic-8080" namespace:"gloo-system" references the service "petclinic" which does not exist in namespace "bad-namespace"
```

But the pod has not crashed after several minutes.  I'll try some other approaches as well.

**Comment by jameshbarton** [comment]
Instructions to Reproduce:

All files references are available in this [bug.zip](https://github.com/solo-io/gloo/files/5730757/bug.zip).

1. Patch Gloo settings to restrict `watchNamespaces` to `gloo-system` and `app`.
`kubectl patch -n gloo-system settings default --type merge --patch "$(cat settings-patch-2.yaml)"`

2. Create namespace `app`.
`kubectl create ns app`

3. Create upstream that point to kube service in non-existent namespace.  (This was originally unintentional; the user fat-fingered this Upstream spec to point to the wrong namespace.)
`kubectl apply -f usbug.yaml`

4.  Observe that `glooctl check` reports no errors.  It does not detect the dangling reference in the upstream.  Expected behavior is that this error would be reported.

5. Create virtual service that points to the just-created upstream.
`kubectl apply -f vsbug.yaml`

6. Observe that the gloo pod panics as shown in logs below.  Expected behavior is for gloo to detect and report this gracefully with no panic.
```
{"level":"warn","ts":1608649233.1642292,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer.kubernetes_eds","caller":"kubernetes/eds.go:101","msg":"namespace is not watched, and has upstreams pointing to it","version":"1.5.14","namespace":"app-bla"}
{"level":"error","ts":1608649233.1643255,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer.kubernetes_eds","caller":"kubernetes/eds.go:206","msg":"upstream app.tpsvc-public-api-80: port 80 not found for service tpsvc-public-api","version":"1.5.14","stacktrace":"github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.filterEndpoints\n\t/go/pkg/mod/github.com/solo-io/gloo@v1.5.14/projects/gloo/pkg/plugins/kubernetes/eds.go:206\ngithub.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*edsWatcher).List\n\t/go/pkg/mod/github.com/solo-io/gloo@v1.5.14/projects/gloo/pkg/plugins/kubernetes/eds.go:121\ngithub.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*edsWatcher).watch.func1\n\t/go/pkg/mod/github.com/solo-io/gloo@v1.5.14/projects/gloo/pkg/plugins/kubernetes/eds.go:130\ngithub.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*edsWatcher).watch.func2\n\t/go/pkg/mod/github.com/solo-io/gloo@v1.5.14/projects/gloo/pkg/plugins/kubernetes/eds.go:157"}
{"level":"info","ts":1608649233.215895,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.envoyTranslatorSyncer","caller":"syncer/envoy_translator_syncer.go:77","msg":"begin sync 14902748162430009336 (0 proxies, 17 upstreams, 16 endpoints, 1 secrets, 6 artifacts, 0 auth configs, 0 rate limit configs)","version":"1.5.14"}
{"level":"info","ts":1608649233.25213,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.envoyTranslatorSyncer","caller":"syncer/envoy_translator_syncer.go:188","msg":"end sync 14902748162430009336","version":"1.5.14"}
{"level":"info","ts":1608649233.2527757,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.rateLimitTranslatorSyncer","caller":"ratelimit/ratelimit_translator_syncer.go:97","msg":"begin rate limit sync 14902748162430009336 (0 proxies, 0 rate limit configs)","version":"1.5.14"}
{"level":"info","ts":1608649233.2530456,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.rateLimitTranslatorSyncer","caller":"ratelimit/ratelimit_translator_syncer.go:174","msg":"end sync 14902748162430009336","version":"1.5.14"}
{"level":"info","ts":1608649233.254138,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.extAuthTranslatorSyncer","caller":"extauth/extauth_translator_syncer.go:36","msg":"begin auth sync 14902748162430009336 (0 proxies, 17 upstreams, 16 endpoints, 1 secrets, 6 artifacts, 0 auth configs)","version":"1.5.14"}
{"level":"info","ts":1608649233.2542017,"logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.extAuthTranslatorSyncer","caller":"extauth/extauth_translator_syncer.go:40","msg":"end auth sync 14902748162430009336","version":"1.5.14"}

{"level":"info","ts":1608649324.1385274,"logger":"proxy-validator","caller":"validation/server.go:170","msg":"received proxy validation request"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x25c21d3]

goroutine 5691 [running]:
github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*plugin).ProcessUpstream(0xc00172bac0, 0x400b260, 0xc001a07590, 0xc0015e4600, 0xc0019ffb00, 0xc000516b40, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.5.14/projects/gloo/pkg/plugins/kubernetes/plugin.go:64 +0x193
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorInstance).computeCluster(0xc001adcf58, 0x400b260, 0xc001a07590, 0xc0015e4600, 0xc0019ffb00, 0xc001a073b0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.5.14/projects/gloo/pkg/translator/clusters.go:61 +0x2d1
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorInstance).computeClusters(0xc001adcf58, 0x400b260, 0xc001a07560, 0xc0015e4600, 0xc001a073b0, 0xc0018c77a0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.5.14/projects/gloo/pkg/translator/clusters.go:40 +0x395
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorInstance).Translate(0xc001adcf58, 0x400b260, 0xc001a07260, 0xc0015e4600, 0xc0018c77a0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/solo-io/gloo@v1.5.14/projects/gloo/pkg/translator/translator.go:81 +0x695
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorFactory).Translate(0xc000c4c280, 0x400b260, 0xc001a06f00, 0xc0015e4600, 0xc0018c77a0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/solo-io/gloo@v1.5.14/projects/gloo/pkg/translator/translator.go:47 +0x1b9
github.com/solo-io/gloo/projects/gloo/pkg/validation.(*validator).ValidateProxy(0xc00165f590, 0x400b260, 0xc001a06f00, 0xc0018da5d0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.5.14/projects/gloo/pkg/validation/server.go:171 +0x2a8
github.com/solo-io/gloo/projects/gloo/pkg/validation.(*validationServer).ValidateProxy(0xc001248570, 0x400b260, 0xc0018da5a0, 0xc0018da5d0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.5.14/projects/gloo/pkg/validation/server.go:218 +0xe0
github.com/solo-io/gloo/projects/gloo/pkg/api/grpc/validation._ProxyValidationService_ValidateProxy_Handler(0x3433fe0, 0xc001248570, 0x400b260, 0xc0018da5a0, 0xc001ad4c00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.5.14/projects/gloo/pkg/api/grpc/validation/proxy_validation.pb.go:1264 +0x3df
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0009709c0, 0x4025d80, 0xc000d03800, 0xc0019a2000, 0xc0017e0e70, 0x595c890, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0x1035
google.golang.org/grpc.(*Server).handleStream(0xc0009709c0, 0x4025d80, 0xc000d03800, 0xc0019a2000, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0x976
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0011937b0, 0xc0009709c0, 0x4025d80, 0xc000d03800, 0xc0019a2000)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xf4
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xb0
```

Context:
- Gloo version
```
% glooctl version
Client: {"version":"1.5.14"}
Server: {"type":"Gateway","enterprise":true,"kubernetes":{"containers":[{"Tag":"1.5.14","Name":"grpcserver-ui","Registry":"quay.io/solo-io"},{"Tag":"1.5.14","Name":"grpcserver-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.14","Name":"grpcserver-envoy","Registry":"quay.io/solo-io"},{"Tag":"1.5.14","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.5.14","Name":"extauth-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.14","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.5.14","Name":"gloo-ee-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.5.14","Name":"gloo-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.14","Name":"observability-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.14","Name":"rate-limit-ee","Registry":"quay.io/solo-io"},{"Tag":"5","Name":"redis","Registry":"docker.io"}],"namespace":"gloo-system"}}
```
- Kubernetes version v1.18.2 (kind)

Thanks @law10k for your support in reproducing this.
