### ISSUE TITLE
GraphQL schema discovery not working

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#5972]
### Gloo Edge Version

1.11.x (beta)

### Describe the bug

GraphQL schema discovery not working (beta 6)

it may be related to the NP in the discovery svc: 
```
{"level":"info","ts":"2022-02-23T17:22:20.060Z","logger":"uds.v1.event_loop.uds","caller":"discovery/discovery.go:154","msg":"reconciled upstreams","version":"undefined","discovered_by":"kubernetesplugin","upstreams":21}
2022/02/23 17:22:26 http: panic serving 127.0.0.1:46126: runtime error: invalid memory address or nil pointer dereference
goroutine 311 [running]:
net/http.(*conn).serve.func1(0xc0017380a0)
	/usr/local/go/src/net/http/server.go:1824 +0x14c
panic(0x3d06900, 0x5e1b550)
	/usr/local/go/src/runtime/panic.go:971 +0x4c7
go.uber.org/atomic.(*Int32).Store(0x0, 0xc0ffffffff)
	/go/pkg/mod/go.uber.org/atomic@v1.9.0/int32.go:75 +0x5
go.uber.org/zap.AtomicLevel.SetLevel(0x0, 0xff)
	/go/pkg/mod/go.uber.org/zap@v1.19.1/level.go:102 +0x35
go.uber.org/zap.AtomicLevel.ServeHTTP(0x0, 0x46aa180, 0xc00076e0e0, 0xc000911500)
	/go/pkg/mod/go.uber.org/zap@v1.19.1/http_handler.go:90 +0x3a5
net/http.(*ServeMux).ServeHTTP(0xc0008ea000, 0x46aa180, 0xc00076e0e0, 0xc000911500)
	/usr/local/go/src/net/http/server.go:2448 +0x1ab
net/http.serverHandler.ServeHTTP(0xc00076e000, 0x46aa180, 0xc00076e0e0, 0xc000911500)
	/usr/local/go/src/net/http/server.go:2887 +0x22b
net/http.(*conn).serve(0xc0017380a0, 0x46af330, 0xc001adfdc0)
	/usr/local/go/src/net/http/server.go:1952 +0x1c25
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x96e
2022/02/23 17:22:26 http: panic serving 127.0.0.1:46128: runtime error: invalid memory address or nil pointer dereference
```

### Steps to reproduce the bug

label a service that as a swagger
example 

```
kubectl label service petstore discovery.solo.io/function_discovery=enabled
```

### Expected Behavior

a GraphQL schema should be created

**Comment by saiskee** [comment]
Fixed in 1.11.0-beta13 by editing schema crds.
