### ISSUE TITLE
gateway_test: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#6237]
### Gloo Edge Version

1.11.x (beta)

### Describe the bug

```
Step #10 - "test": • [SLOW TEST:8.036 seconds]
Step #10 - "test": Gateway in memory http gateway won't allow a bad authconfig in a virtualservice to block updates to a gateway 
Step #10 - "test": /workspace/gloo/test/e2e/gateway_test.go:212
Step #10 - "test": ------------------------------
Step #10 - "test": • [SLOW TEST:13.049 seconds]
Step #10 - "test": Gateway in memory http gateway traffic works when rapid virtual service creation and deletion causes no race conditions 
Step #10 - "test": /workspace/gloo/test/e2e/gateway_test.go:367
Step #10 - "test": ------------------------------
Step #10 - "test": • [SLOW TEST:5.163 seconds]
Step #10 - "test": Gateway in memory http gateway traffic should work with no ssl and clean up the envoy config when the virtual service is deleted 
Step #10 - "test": /workspace/gloo/test/e2e/gateway_test.go:413
Step #10 - "test": ------------------------------
Step #10 - "test": ••••panic: runtime error: invalid memory address or nil pointer dereference
Step #10 - "test": [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5124816]
Step #10 - "test": 
Step #10 - "test": goroutine 22392 [running]:
Step #10 - "test": github.com/solo-io/gloo/projects/gateway/pkg/validation.(*connectionRefreshingValidationClient).Validate.func1(0x0, 0x0, 0xc0095af170, 0x0)
Step #10 - "test": 	/workspace/gloo/projects/gateway/pkg/validation/robust_client.go:66 +0x56
Step #10 - "test": github.com/solo-io/gloo/projects/gateway/pkg/validation.(*connectionRefreshingValidationClient).retryWithNewClient.func1(0x0, 0x0)
Step #10 - "test": 	/workspace/gloo/projects/gateway/pkg/validation/robust_client.go:88 +0x155
Step #10 - "test": github.com/avast/retry-go.Do(0xc0095af398, 0xc0095af388, 0x2, 0x2, 0x1, 0xc007b8fb30)
Step #10 - "test": 	/go/pkg/mod/github.com/avast/retry-go@v2.4.3+incompatible/retry.go:103 +0x247
Step #10 - "test": github.com/solo-io/gloo/projects/gateway/pkg/validation.(*connectionRefreshingValidationClient).retryWithNewClient(0xc000f9a360, 0x75297c0, 0xc007b8fb30, 0xc0095af418, 0x75297c0, 0xc007b8fb30)
Step #10 - "test": 	/workspace/gloo/projects/gateway/pkg/validation/robust_client.go:84 +0x2ee
Step #10 - "test": github.com/solo-io/gloo/projects/gateway/pkg/validation.(*connectionRefreshingValidationClient).Validate(0xc000f9a360, 0x75297c0, 0xc007b8edb0, 0xc0041f82c0, 0x0, 0x0, 0x0, 0xc0095af4f8, 0x1a4d7b9, 0xc006947200)
Step #10 - "test": 	/workspace/gloo/projects/gateway/pkg/validation/robust_client.go:64 +0x125
Step #10 - "test": github.com/solo-io/gloo/projects/gateway/pkg/reconciler.(*proxyReconciler).addProxyValidationResults(0xc001054c90, 0x75297c0, 0xc007b8edb0, 0xc007b8fa40, 0x0, 0x90)
Step #10 - "test": 	/workspace/gloo/projects/gateway/pkg/reconciler/proxy_reconciler.go:113 +0x26a
Step #10 - "test": github.com/solo-io/gloo/projects/gateway/pkg/reconciler.(*proxyReconciler).ReconcileProxies(0xc001054c90, 0x75297c0, 0xc007b8edb0, 0xc007b8fa40, 0x6847633, 0xb, 0xc001054e10, 0xc0041f4840, 0xc0041f4840)
Step #10 - "test": 	/workspace/gloo/projects/gateway/pkg/reconciler/proxy_reconciler.go:46 +0x7d
Step #10 - "test": github.com/solo-io/gloo/projects/gateway/pkg/syncer.(*translatorSyncer).reconcile(0xc0039d8870, 0x75297c0, 0xc007b8edb0, 0xc007b8fa40, 0xc007b8fa70, 0xc007b8fa70, 0x1)
Step #10 - "test": 	/workspace/gloo/projects/gateway/pkg/syncer/translator_syncer.go:120 +0xf8
Step #10 - "test": github.com/solo-io/gloo/projects/gateway/pkg/syncer.(*translatorSyncer).Sync(0xc0039d8870, 0x7529718, 0xc007b8edb0, 0xc003892000, 0x0, 0x0)
Step #10 - "test": 	/workspace/gloo/projects/gateway/pkg/syncer/translator_syncer.go:81 +0x5a5
Step #10 - "test": github.com/solo-io/gloo/projects/gateway/pkg/api/v1.ApiSyncers.Sync(0xc0055a5f80, 0x2, 0x2, 0x7529718, 0xc0034bd500, 0xc003892000, 0x0, 0x0)
Step #10 - "test": 	/workspace/gloo/projects/gateway/pkg/api/v1/api_event_loop.sk.go:28 +0xc2
Step #10 - "test": github.com/solo-io/gloo/projects/gateway/pkg/api/v1.(*apiEventLoop).Run.func1(0xc0012e3080, 0x75297c0, 0xc001054e70, 0x0, 0xdf8475800, 0x0, 0x0, 0xc001054e40, 0xc007f91e00, 0xc007c1a378)
Step #10 - "test": 	/workspace/gloo/projects/gateway/pkg/api/v1/api_event_loop.sk.go:84 +0x2e6
Step #10 - "test": created by github.com/solo-io/gloo/projects/gateway/pkg/api/v1.(*apiEventLoop).Run
Step #10 - "test": 	/workspace/gloo/projects/gateway/pkg/api/v1/api_event_loop.sk.go:66 +0x3e5
```
logs: https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=ca4e2351-d104-4160-93f4-1883bd9f388b

### Steps to reproduce the bug

seen in ci

### Expected Behavior

test should pass

**Comment by inFocus7** [comment]
encountered this flake as well. logs: https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=14ac962b-0346-460f-93c5-0f6194111c59
