### ISSUE TITLE
[GraphQL] Envoy Segfault when receiving a bad configuration from a resolver

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#6978]
### Gloo Edge Version

1.12.x (latest stable)

### Describe the bug

When using a stitched schema, using a remote schema, a segfault will be thrown if the backend gql sever returns an non 2xx response

```
(/usr/src/app/node_modules/apollo-server/node_modules/apollo-server-core/dist/runHttpQuery.js:187:30)"]}}}]}

[2022-08-17 16:28:21.639][30][debug][filter] [source/graphql/common/execution/remote_executor.cc:117] [C10][S8218455515855568198] [GraphQL|remote_execution] remote execution result: 400 - '{"errors":[{"message":"Syntax Error: Unexpected \"$\".","extensions":{"code":"GRAPHQL_PARSE_FAILED","exception":{"stacktrace":["GraphQLError: Syntax Error: Unexpected \"$\".","    at syntaxError (/usr/src/app/node_modules/graphql/error/syntaxError.js:15:10)","    at Parser.unexpected (/usr/src/app/node_modules/graphql/language/parser.js:1471:41)","    at Parser.parseDefinition (/usr/src/app/node_modules/graphql/language/parser.js:161:16)","    at Parser.many (/usr/src/app/node_modules/graphql/language/parser.js:1523:26)","    at Parser.parseDocument (/usr/src/app/node_modules/graphql/language/parser.js:115:25)","    at parse (/usr/src/app/node_modules/graphql/language/parser.js:31:17)","    at parse (/usr/src/app/node_modules/apollo-server/node_modules/apollo-server-core/dist/requestPipeline.js:178:36)","    at processGraphQLRequest (/usr/src/app/node_modules/apollo-server/node_modules/apollo-server-core/dist/requestPipeline.js:82:39)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async processHTTPRequest (/usr/src/app/node_modules/apollo-server/node_modules/apollo-server-core/dist/runHttpQuery.js:187:30)"]}}}]}
'
[*** LOG ERROR #0001 ***] [2022-08-17 16:28:21] [filter] {invalid format string}
[2022-08-17 16:28:21.643][30][debug][filter] [./source/extensions/graphql/resolvers/stitching/stitching_resolver_handle.h:80] [C10][S8218455515855568198] [GraphQL|stitching_resolver] transformResult: responseKey: getUserDetails
[2022-08-17 16:28:21.644][30][critical][main] [external/envoy/source/exe/terminate_handler.cc:12] std::terminate called! (possible uncaught exception, see trace)
[2022-08-17 16:28:21.644][30][critical][backtrace] [external/envoy/source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2022-08-17 16:28:21.644][30][critical][backtrace] [external/envoy/source/server/backtrace.h:92] Envoy version: 7344d1dae4b75f032f0b9c8657937491397e47ca/1.23.0-dev/Distribution/RELEASE/BoringSSL
[2022-08-17 16:28:21.646][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #0: [0x4003844fbc]
[2022-08-17 16:28:21.646][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #1: [0x4003d2dd73]
[2022-08-17 16:28:21.647][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #2: [0x4001931017]
[2022-08-17 16:28:21.648][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #3: [0x4001930858]
[2022-08-17 16:28:21.649][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #4: [0x40019c077a]
[2022-08-17 16:28:21.649][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #5: [0x40019bf895]
[2022-08-17 16:28:21.650][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #6: [0x40033b6a29]
[2022-08-17 16:28:21.650][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #7: [0x40033b6026]
[2022-08-17 16:28:21.650][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #8: [0x40033e77dc]
[2022-08-17 16:28:21.651][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #9: [0x40031331f2]
[2022-08-17 16:28:21.652][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #10: [0x40031331f2]
[2022-08-17 16:28:21.652][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #11: [0x4003329b91]
[2022-08-17 16:28:21.653][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #12: [0x400332512d]
[2022-08-17 16:28:21.653][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #13: [0x4003324e68]
[2022-08-17 16:28:21.654][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #14: [0x40036e1b84]
[2022-08-17 16:28:21.654][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #15: [0x40033232d4]
[2022-08-17 16:28:21.655][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #16: [0x4003322b2f]
[2022-08-17 16:28:21.656][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #17: [0x400332269d]
[2022-08-17 16:28:21.656][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #18: [0x40031d6ead]
[2022-08-17 16:28:21.656][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #19: [0x40031d8185]
[2022-08-17 16:28:21.657][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #20: [0x40035de495]
[2022-08-17 16:28:21.658][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #21: [0x40035d6a6e]
[2022-08-17 16:28:21.659][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #22: [0x40035d4873]
[2022-08-17 16:28:21.659][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #23: [0x40035c7871]
[2022-08-17 16:28:21.660][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #24: [0x40035c8c3d]
[2022-08-17 16:28:21.660][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #25: [0x40036dbb40]
[2022-08-17 16:28:21.660][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #26: [0x40036da481]
[2022-08-17 16:28:21.661][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #27: [0x4002f0aa9f]
[2022-08-17 16:28:21.661][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #28: [0x40038df203]
[2022-08-17 16:28:21.662][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #29: [0x40062fd2d6]
[2022-08-17 16:28:21.663][30][critical][backtrace] [external/envoy/source/server/backtrace.h:104] Caught Aborted, suspect faulting address 0x277500000009
[2022-08-17 16:28:21.663][30][critical][backtrace] [external/envoy/source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2022-08-17 16:28:21.663][30][critical][backtrace] [external/envoy/source/server/backtrace.h:92] Envoy version: 7344d1dae4b75f032f0b9c8657937491397e47ca/1.23.0-dev/Distribution/RELEASE/BoringSSL
[2022-08-17 16:28:21.664][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #0: [0x4006307930]
[2022-08-17 16:28:21.664][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #1: [0x4003d2dd73]
[2022-08-17 16:28:21.665][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #2: [0x4001931017]
[2022-08-17 16:28:21.665][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #3: [0x4001930858]
[2022-08-17 16:28:21.665][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #4: [0x40019c077a]
[2022-08-17 16:28:21.666][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #5: [0x40019bf895]
[2022-08-17 16:28:21.666][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #6: [0x40033b6a29]
[2022-08-17 16:28:21.667][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #7: [0x40033b6026]
[2022-08-17 16:28:21.668][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #8: [0x40033e77dc]
[2022-08-17 16:28:21.668][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #9: [0x40031331f2]
[2022-08-17 16:28:21.668][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #10: [0x40031331f2]
[2022-08-17 16:28:21.669][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #11: [0x4003329b91]
[2022-08-17 16:28:21.670][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #12: [0x400332512d]
[2022-08-17 16:28:21.670][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #13: [0x4003324e68]
[2022-08-17 16:28:21.671][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #14: [0x40036e1b84]
[2022-08-17 16:28:21.671][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #15: [0x40033232d4]
[2022-08-17 16:28:21.671][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #16: [0x4003322b2f]
[2022-08-17 16:28:21.672][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #17: [0x400332269d]
[2022-08-17 16:28:21.673][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #18: [0x40031d6ead]
[2022-08-17 16:28:21.673][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #19: [0x40031d8185]
[2022-08-17 16:28:21.674][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #20: [0x40035de495]
[2022-08-17 16:28:21.674][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #21: [0x40035d6a6e]
[2022-08-17 16:28:21.675][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #22: [0x40035d4873]
[2022-08-17 16:28:21.675][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #23: [0x40035c7871]
[2022-08-17 16:28:21.676][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #24: [0x40035c8c3d]
[2022-08-17 16:28:21.677][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #25: [0x40036dbb40]
[2022-08-17 16:28:21.677][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #26: [0x40036da481]
[2022-08-17 16:28:21.678][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #27: [0x4002f0aa9f]
[2022-08-17 16:28:21.678][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #28: [0x40038df203]
[2022-08-17 16:28:21.679][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #29: [0x40062fd2d6]
AsyncClient 0x4428fefd0110, stream_id_: 12400280774541898531
&stream_info_: 
  StreamInfoImpl 0x4428fefd02f0, protocol_: 1, response_code_: 400, response_code_details_: via_upstream, attempt_count_: 1, health_check_request_: 0, route_name_:   upstream_info_: 
    UpstreamInfoImpl 0x4428fdd3dc98, upstream_connection_id_: 18
Http1::ConnectionImpl 0x4428fdd46008, dispatching_: 1, dispatching_slice_already_drained_: 0, reset_stream_called_: 0, handling_upgrade_: 0, deferred_end_stream_headers_: 0, processing_trailers_: 0, buffered_body_.length(): 0, header_parsing_state_: Done, current_header_field_: , current_header_value_: 
absl::get<ResponseHeaderMapPtr>(headers_or_trailers_): null
Dumping corresponding downstream request:
decoder: 
[2022-08-17 16:28:21.681][30][critical][backtrace] [external/envoy/source/server/backtrace.h:104] Caught Segmentation fault, suspect faulting address 0x0
[2022-08-17 16:28:21.681][30][critical][backtrace] [external/envoy/source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2022-08-17 16:28:21.681][30][critical][backtrace] [external/envoy/source/server/backtrace.h:92] Envoy version: 7344d1dae4b75f032f0b9c8657937491397e47ca/1.23.0-dev/Distribution/RELEASE/BoringSSL
[2022-08-17 16:28:21.683][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #0: [0x4006307930]
[2022-08-17 16:28:21.683][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #1: [0x4003325750]
[2022-08-17 16:28:21.683][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #2: [0x40035c6038]
[2022-08-17 16:28:21.684][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #3: [0x40036f982d]
[2022-08-17 16:28:21.684][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #4: [0x40036f6107]
[2022-08-17 16:28:21.684][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #5: [0x4006307930]
[2022-08-17 16:28:21.685][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #6: [0x4003d2dd73]
[2022-08-17 16:28:21.685][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #7: [0x4001931017]
[2022-08-17 16:28:21.685][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #8: [0x4001930858]
[2022-08-17 16:28:21.686][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #9: [0x40019c077a]
[2022-08-17 16:28:21.686][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #10: [0x40019bf895]
[2022-08-17 16:28:21.686][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #11: [0x40033b6a29]
[2022-08-17 16:28:21.687][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #12: [0x40033b6026]
[2022-08-17 16:28:21.687][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #13: [0x40033e77dc]
[2022-08-17 16:28:21.688][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #14: [0x40031331f2]
[2022-08-17 16:28:21.689][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #15: [0x40031331f2]
[2022-08-17 16:28:21.689][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #16: [0x4003329b91]
[2022-08-17 16:28:21.689][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #17: [0x400332512d]
[2022-08-17 16:28:21.690][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #18: [0x4003324e68]
[2022-08-17 16:28:21.691][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #19: [0x40036e1b84]
[2022-08-17 16:28:21.691][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #20: [0x40033232d4]
[2022-08-17 16:28:21.692][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #21: [0x4003322b2f]
[2022-08-17 16:28:21.692][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #22: [0x400332269d]
[2022-08-17 16:28:21.693][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #23: [0x40031d6ead]
[2022-08-17 16:28:21.693][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #24: [0x40031d8185]
[2022-08-17 16:28:21.694][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #25: [0x40035de495]
[2022-08-17 16:28:21.694][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #26: [0x40035d6a6e]
[2022-08-17 16:28:21.695][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #27: [0x40035d4873]
[2022-08-17 16:28:21.695][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #28: [0x40035c7871]
[2022-08-17 16:28:21.696][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #29: [0x40035c8c3d]
[2022-08-17 16:28:21.696][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #30: [0x40036dbb40]
[2022-08-17 16:28:21.697][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #31: [0x40036da481]
[2022-08-17 16:28:21.697][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #32: [0x4002f0aa9f]
[2022-08-17 16:28:21.697][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #33: [0x40038df203]
[2022-08-17 16:28:21.698][30][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #34: [0x40062fd2d6]
Our FatalActions triggered a fatal signal.
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

```

### Steps to reproduce the bug

Use the following example: 

https://github.com/asayah/gloo-graphql-example/tree/main/kube/labs/3-imperative_and_stitched

- deploy all the services 
- then deploy all the labs 

then execute the following gql query:

```

query {
  getBlogs {
    id
    content
    comments {
        comment
        user {
            username
            firstname
            
        }
    }
    user { 
        username
        
        
    }
    title
  }

}

```

### Expected Behavior

No segfault

**Comment by saiskee** [comment]
Fixed in envoy-gloo-ee 1.23.0-patch7 https://github.com/solo-io/envoy-gloo-ee/releases/tag/v1.23.0-patch7
