### ISSUE TITLE
SIGSEGV checking OIDC token expiration 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#8378]
### Gloo Edge Version

1.14.x (latest stable)

### Kubernetes Version

None

### Describe the bug

SIGSEGV from extauth OIDC:

```
{"level":"info","ts":1686301890.109225,"logger":"ext-auth.ext-auth-service","msg":"Failed to validate token","version":"undefined","x-request-id":"74f20d14-76ba-98d6-9326-69c85481bed2"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x43d83ef]

goroutine 127744 [running]:
github.com/solo-io/ext-auth-service/pkg/config/oidc.(*RequestAuthorizer).isTokenAboutToExpire(0xc001845b40, 0x0)
	/go/pkg/mod/github.com/solo-io/ext-auth-service@v0.35.1/pkg/config/oidc/oidc_request.go:754 +0x4f
github.com/solo-io/ext-auth-service/pkg/config/oidc.(*RequestAuthorizer).shouldRefreshToken(0xc001845b40, 0x0, {0x5142c60, 0xc0015b18f0})
	/go/pkg/mod/github.com/solo-io/ext-auth-service@v0.35.1/pkg/config/oidc/oidc_request.go:772 +0x77
github.com/solo-io/ext-auth-service/pkg/config/oidc.(*RequestAuthorizer).checkAuthenticationHeaderAuthorized(0xc001845b40, {0xc0003f0787, 0x40})
	/go/pkg/mod/github.com/solo-io/ext-auth-service@v0.35.1/pkg/config/oidc/oidc_request.go:783 +0x1c9
github.com/solo-io/ext-auth-service/pkg/config/oidc.(*RequestAuthorizer).areHeadersAuthorized(0xc001a63b40, 0xc0015b16b0)
	/go/pkg/mod/github.com/solo-io/ext-auth-service@v0.35.1/pkg/config/oidc/oidc_request.go:628 +0x51f
github.com/solo-io/ext-auth-service/pkg/config/oidc.(*RequestAuthorizer).checkHttpRequestAuthorized(0xc001a63b40, 0xc0002d7a40)
	/go/pkg/mod/github.com/solo-io/ext-auth-service@v0.35.1/pkg/config/oidc/oidc_request.go:471 +0x25f
github.com/solo-io/ext-auth-service/pkg/config/oidc.(*RequestAuthorizer).checkNetworkRequestAuthorized(0xc001a63b40, 0xc001815bc0)
	/go/pkg/mod/github.com/solo-io/ext-auth-service@v0.35.1/pkg/config/oidc/oidc_request.go:157 +0x4b
github.com/solo-io/ext-auth-service/pkg/config/oidc.(*RequestAuthorizer).areAttributesAuthorized(0xc001a63b40)
	/go/pkg/mod/github.com/solo-io/ext-auth-service@v0.35.1/pkg/config/oidc/oidc_request.go:150 +0x107
github.com/solo-io/ext-auth-service/pkg/config/oidc.(*RequestAuthorizer).CheckRequestAuthorized(0xc001845b40)
	/go/pkg/mod/github.com/solo-io/ext-auth-service@v0.35.1/pkg/config/oidc/oidc_request.go:135 +0x45
github.com/solo-io/ext-auth-service/pkg/config/oidc.(*IssuerImpl).Authorize(0xc000612c00, {0x517de88, 0xc0015b1860}, 0xc00182f2e0)
	/go/pkg/mod/github.com/solo-io/ext-auth-service@v0.35.1/pkg/config/oidc/oidc.go:295 +0x485
github.com/solo-io/ext-auth-service/pkg/chain.(*identityAuthorizerImpl).Authorize(0xc000c4bdb0, {0x517de88, 0xc0015b17d0}, 0xc00182f2e0, 0xc000e31c80)
	/go/pkg/mod/github.com/solo-io/ext-auth-service@v0.35.1/pkg/chain/chain.go:367 +0x1b3
github.com/solo-io/ext-auth-service/pkg/chain.(*authServiceChain).Authorize(0xc00020fe50, {0x517de88, 0xc0015b17d0}, 0xc00182f2e0)
	/go/pkg/mod/github.com/solo-io/ext-auth-service@v0.35.1/pkg/chain/chain.go:112 +0xba
github.com/solo-io/ext-auth-service/pkg/service.(*authServer).Check(0xc000344200, {0x517de88, 0xc0015b17d0}, 0xc0015b1680)
	/go/pkg/mod/github.com/solo-io/ext-auth-service@v0.35.1/pkg/service/extauth.go:147 +0x527
github.com/envoyproxy/go-control-plane/envoy/service/auth/v3._Authorization_Check_Handler.func1({0x517de88, 0xc0015b17a0}, {0x4c44580, 0xc0015b1680})
	/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.11.0/envoy/service/auth/v3/external_auth.pb.go:699 +0xfa
github.com/solo-io/go-utils/healthchecker.GrpcUnaryServerHealthCheckerInterceptor.func1({0x517de88, 0xc0015b17a0}, {0x4c44580, 0xc0015b1680}, 0xc00169fd40, 0xc000fcbe90)
	/go/pkg/mod/github.com/solo-io/go-utils@v0.24.0/healthchecker/grpc.go:69 +0x30b
google.golang.org/grpc.getChainUnaryHandler.func1({0x517de88, 0xc0015b17a0}, {0x4c44580, 0xc0015b1680})
	/go/pkg/mod/google.golang.org/grpc@v1.52.0/server.go:1163 +0x137
github.com/solo-io/ext-auth-service/pkg/server.requestIdInterceptor.func1({0x517de88, 0xc0015b17a0}, {0x4c44580, 0xc0015b1680}, 0xc00169fd40, 0xc001815dc0)
	/go/pkg/mod/github.com/solo-io/ext-auth-service@v0.35.1/pkg/server/logging.go:86 +0x449
google.golang.org/grpc.getChainUnaryHandler.func1({0x517de88, 0xc0015b1740}, {0x4c44580, 0xc0015b1680})
	/go/pkg/mod/google.golang.org/grpc@v1.52.0/server.go:1163 +0x137
github.com/grpc-ecosystem/go-grpc-middleware/logging/zap.UnaryServerInterceptor.func1({0x517de88, 0xc0015b1650}, {0x4c44580, 0xc0015b1680}, 0xc00169fd40, 0xc001815cc0)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/logging/zap/server_interceptors.go:31 +0x19d
google.golang.org/grpc.chainUnaryInterceptors.func1({0x517de88, 0xc0015b1650}, {0x4c44580, 0xc0015b1680}, 0xc00169fd40, 0xc000fcbe90)
	/go/pkg/mod/google.golang.org/grpc@v1.52.0/server.go:1154 +0x11b
github.com/envoyproxy/go-control-plane/envoy/service/auth/v3._Authorization_Check_Handler({0x4b82800, 0xc000344200}, {0x517de88, 0xc0015b1650}, 0xc0015d70a0, 0xc0002f8120)
	/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.11.0/envoy/service/auth/v3/external_auth.pb.go:701 +0x225
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0006d6000, {0x51857f0, 0xc000f73520}, 0xc001823440, 0xc000592390, 0x66218e0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.52.0/server.go:1336 +0x1504
google.golang.org/grpc.(*Server).handleStream(0xc0006d6000, {0x51857f0, 0xc000f73520}, 0xc001823440, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.52.0/server.go:1704 +0x888
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/pkg/mod/google.golang.org/grpc@v1.52.0/server.go:965 +0x109
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.52.0/server.go:963 +0x366 
```

### Steps to reproduce the bug

TBD

### Expected Behavior

No SIGSEGV

**Comment by mithie** [comment]
This also happens with Gloo version 1.13.9

**Comment by sam-heilbron** [comment]
This is, or will be available in the following Gloo Edge Enterprise versions:
- v1.13.20
- v1.14.7
- v1.15.0-beta4
